# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html
c.statusbar.show = "in-mode"; 
config.load_autoconfig()
c.tabs.show = "switching"
# Uncomment this to still load settings configured via autoconfig.yml
c.url.start_pages = "file:///home/pablo/Documentos/mientras/index.html"
c.url.searchengines = {"DEFAULT": "https://google.com/search?q={}"}
c.url.default_page = "file:///home/pablo/Documentos/mientras/index.html"
#FONTS
c.fonts.tabs.selected = '8pt cherry'
c.fonts.tabs.unselected = '8pt cherry'
c.fonts.hints = '8pt cherry'
c.fonts.keyhint = '8pt cherry'
c.fonts.prompts = '8pt cherry'
c.fonts.downloads = '8pt cherry'
c.fonts.statusbar = '8pt cherry'
c.fonts.contextmenu = '8ptcherrye'
c.fonts.messages.info = '8pt cherry'
c.fonts.debug_console = '8pt cherry'
c.fonts.completion.entry = '8pt cherry'
c.fonts.completion.category = '8pt cherry'


config.source('qutewal.py')
